export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const PRODUCT_START = ' PRODUCT_START';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';

export const CUSTOMER_START = ' CUSTOMER_START';
export const CUSTOMER_SUCCESS = 'CUSTOMER_SUCCESS';
export const CUSTOMER_FAIL = 'CUSTOMER_FAIL';

export const ROUTE_START = ' ROUTE_START';
export const ROUTE_SUCCESS = 'ROUTE_SUCCESS';
export const ROUTE_FAIL = 'ROUTE_FAIL';

export const INVENTORY_START = ' INVENTORY_START';
export const INVENTORY_SUCCESS = 'INVENTORY_SUCCESS';
export const INVENTORY_FAIL = 'INVENTORY_FAIL';